Repository InvArch/InvArch-Frames, pull requests merged in 2021-09, with the labels that each got.

#41 Changed the IPT data to a hash for the IPFS CID
  ipt/src/lib.rs
  ipt/src/mock.rs
  ipt/src/tests.rs
Labels: enhancement

#42 Feat WIP: add set-balance function in ipo pallet
  ipo/src/lib.rs
Labels: enhancement, help wanted

#43 Feat: Add get-balance function in ipo pallet
  ipo/Cargo.toml
  ipo/src/lib.rs
Labels: enhancement, help wanted

#50 Properly configured IPS pallet
  ips/Cargo.toml
  ips/src/lib.rs
  ipt/src/lib.rs
  primitives/src/lib.rs
Labels: enhancement

#52 IPT Tests + Amend Fixed
  ipo/Cargo.toml
  ipo/src/lib.rs
  ipt/src/lib.rs
  ipt/src/mock.rs
  ipt/src/tests.rs
  primitives/src/lib.rs
Labels: bug

#55 Added tests for IPS pallet
  ips/Cargo.toml
  ips/src/lib.rs
  ips/src/mock.rs
  ips/src/tests.rs
  primitives/src/lib.rs
Labels: bug, enhancement

#54 ipo unit testing
  ipo/src/mock.rs
  ipo/src/tests.rs
Labels: enhancement

#56 Fix: refactor weight for dispatchable functions to semi-static
  ipo/src/lib.rs
  ips/src/lib.rs
  ipt/src/lib.rs
Labels: enhancement

#58 Buy function now also transfers the IPTs tied to the IPS
  ips/src/lib.rs
  ips/src/tests.rs
Labels: bug

#59 Adding IpsData type so it defines traits
  ips/src/lib.rs
  ips/src/mock.rs
Labels: enhancement
